
import json
import os

TR_FILE = 'locales/tr.json'

TURKISH_UPDATES = {
    # Buttons
    "save_changes": "Değişiklikleri Kaydet",
    "add_new": "Yeni Ekle",
    "btn_add": "Ekle",
    "btn_cancel": "İptal",
    "btn_delete": "Sil",
    "btn_edit": "Düzenle",
    "btn_update": "Güncelle",
    "btn_view": "Görüntüle",
    "btn_back": "Geri",
    "btn_save": "Kaydet",
    "btn_close": "Kapat",
    "btn_search": "Ara",
    "btn_filter": "Filtrele",
    "btn_export": "Dışa Aktar",
    "btn_import": "İçe Aktar",
    "btn_download": "İndir",
    "btn_upload": "Yükle",
    "btn_add_data": "Veri Ekle",
    "btn_add_goal": "Hedef Ekle",
    "btn_add_user": "Kullanıcı Ekle",
    "btn_add_company": "Şirket Ekle",
    "btn_add_stakeholder": "Paydaş Ekle",
    "sc_add_supplier": "Tedarikçi Ekle",
    "tnfd_add_data_title": "TNFD Verisi Ekle",
    "add_data_btn": "Veri Ekle",
    "create_report_btn": "Rapor Oluştur",
    "data_entry_btn": "Veri Girişi",
    "companies_btn": "Şirketler",
    "messages_btn": "Mesajlar",
    "users_btn": "Kullanıcılar",
    "help_btn": "Yardım",

    # Module Titles & Descriptions
    "prioritization_title": "Önceliklendirme",
    "prioritization_desc": "ESG konularının önceliklendirilmesi ve matris analizi.",
    "water_management_title": "Su Yönetimi",
    "water_management_desc": "Su tüketimi ve geri kazanım takibi.",
    "waste_management_title": "Atık Yönetimi",
    "waste_management_desc": "Atık türleri ve bertaraf yöntemleri yönetimi.",
    "detailed_energy_title": "Enerji Yönetimi",
    "detailed_energy_desc": "Enerji tüketimi ve verimlilik analizi.",
    "emission_calculator_title": "Emisyon Hesaplayıcı",
    "emission_calculator_desc": "Karbon ayak izi hesaplama ve raporlama.",
    "social_title": "Sosyal Performans",
    "social_desc": "Çalışan hakları ve sosyal sorumluluk göstergeleri.",
    "governance_title": "Yönetişim",
    "governance_desc": "Kurumsal yönetim ve uyum süreçleri.",
    "supply_chain_title": "Tedarik Zinciri",
    "supply_chain_desc": "Tedarikçi değerlendirme ve risk yönetimi.",
    "biodiversity_title": "Biyoçeşitlilik",
    "biodiversity_desc": "Doğal yaşamı koruma ve etki analizi.",
    "human_rights_title": "İnsan Hakları",
    "human_rights_desc": "İnsan hakları ihlalleri ve politika takibi.",
    "ohs_title": "İş Sağlığı ve Güvenliği",
    "ohs_desc": "İş kazaları ve güvenlik önlemleri takibi.",
    "training_title": "Eğitim Yönetimi",
    "training_desc": "Çalışan eğitimleri ve gelişim programları.",
    "diversity_title": "Çeşitlilik ve Kapsayıcılık",
    "diversity_desc": "İş gücü çeşitliliği ve fırsat eşitliği.",
    "stakeholder_title": "Paydaş Katılımı",
    "stakeholder_desc": "Paydaş analizi ve iletişim yönetimi.",
    "community_title": "Toplumsal Etki",
    "community_desc": "Toplumla ilişkiler ve sosyal projeler.",
    "product_responsibility_title": "Ürün Sorumluluğu",
    "product_responsibility_desc": "Ürün güvenliği ve müşteri memnuniyeti.",
    "ethics_title": "İş Etiği",
    "ethics_desc": "Etik kurallar ve uyum yönetimi.",
    "risk_management_title": "Risk Yönetimi",
    "risk_management_desc": "Kurumsal risklerin tanımlanması ve yönetimi.",
    "innovation_title": "İnovasyon",
    "innovation_desc": "Ar-Ge projeleri ve yenilikçi uygulamalar.",
    "csrd_compliance_title": "CSRD Uyumu",
    "csrd_compliance_desc": "Kurumsal Sürdürülebilirlik Raporlama Direktifi uyumu.",
    "eu_taxonomy_title": "AB Taksonomisi",
    "eu_taxonomy_desc": "AB Taksonomisi sınıflandırma ve raporlama.",
    "double_materiality_title": "Çifte Önemlilik",
    "double_materiality_desc": "Finansal ve çevresel etki analizi.",
    "gap_analysis_title": "Boşluk Analizi",
    "gap_analysis_desc": "Mevcut durum ve hedefler arasındaki fark analizi.",
    
    # Common Terms
    "dashboard_welcome": "Hoşgeldiniz",
    "dashboard_role": "Rol",
    "system_online": "Sistem Çevrimiçi",
    "quick_access_menu": "Hızlı Erişim",
    "recent_activities": "Son Aktiviteler",
    "login_activity": "Sisteme giriş yapıldı",
    "report_prepared_activity": "Rapor hazırlandı",
    "time_now": "Şimdi",
    "time_2_hours_ago": "2 saat önce",
    "users_title": "Kullanıcılar",
    "companies_title": "Şirketler",
    "reports_title": "Raporlar",
    "messages_title": "Mesajlar",
    "view_details": "Detayları Gör",
    "active": "Aktif",
    "passive": "Pasif",
    "yes": "Evet",
    "no": "Hayır",
    "select": "Seçiniz",
    "select_all": "Tümünü Seç",
    "required": "Zorunlu",
    "optional": "İsteğe Bağlı",
    "description": "Açıklama",
    "date": "Tarih",
    "status": "Durum",
    "actions": "İşlemler",
    "edit": "Düzenle",
    "delete": "Sil",
    "cancel": "İptal",
    "save": "Kaydet",
    "close": "Kapat",
    "search": "Ara",
    "filter": "Filtrele",
    "export": "Dışa Aktar",
    "import": "İçe Aktar",
    "download": "İndir",
    "upload": "Yükle",
    "add": "Ekle",
    "remove": "Kaldır",
    "update": "Güncelle",
    "view": "Görüntüle",
    "back": "Geri",
    "next": "İleri",
    "finish": "Bitir",
    "step": "Adım",
    "of": "/",
    "total": "Toplam",
    "count": "Adet",
    "amount": "Miktar",
    "unit": "Birim",
    "notes": "Notlar",
    "files": "Dosyalar",
    "images": "Resimler",
    "videos": "Videolar",
    "links": "Bağlantılar",
    "comments": "Yorumlar",
    "history": "Geçmiş",
    "created_at": "Oluşturulma Tarihi",
    "updated_at": "Güncellenme Tarihi",
    "created_by": "Oluşturan",
    "updated_by": "Güncelleyen",
    "approved_by": "Onaylayan",
    "rejected_by": "Reddeden",
    "pending": "Bekliyor",
    "approved": "Onaylandı",
    "rejected": "Reddedildi",
    "draft": "Taslak",
    "published": "Yayınlandı",
    "archived": "Arşivlendi",
    "deleted": "Silindi",
    "success": "Başarılı",
    "error": "Hata",
    "warning": "Uyarı",
    "info": "Bilgi",
    "confirm": "Onayla",
    "confirmation": "Onaylama",
    "are_you_sure": "Emin misiniz?",
    "yes_delete": "Evet, Sil",
    "no_cancel": "Hayır, İptal",
    "login": "Giriş Yap",
    "logout": "Çıkış Yap",
    "register": "Kayıt Ol",
    "forgot_password": "Şifremi Unuttum",
    "reset_password": "Şifre Sıfırla",
    "profile": "Profil",
    "settings": "Ayarlar",
    "notifications": "Bildirimler",
    "help": "Yardım",
    "about": "Hakkında",
    "contact": "İletişim",
    "terms": "Kullanım Şartları",
    "privacy": "Gizlilik Politikası",
    "copyright": "Telif Hakkı",
    "all_rights_reserved": "Tüm Hakları Saklıdır",
    "version": "Sürüm",
    "powered_by": "Altyapı",
    "sustainage": "SustainAge",
    "sustainage_desc": "Sürdürülebilirlik Yönetim Platformu",
    
    # Missing Module Titles found in logs
    "product_technology_title": "Ürün Teknolojisi",
    "product_technology_desc": "Ürün teknoloji ve inovasyon yönetimi.",
    "smart_goals_title": "SMART Hedefler",
    "smart_goals_desc": "Ölçülebilir ve ulaşılabilir hedefler.",
    "validation_title": "Doğrulama",
    "validation_desc": "Veri doğrulama ve onay süreçleri.",
    "visualization_title": "Görselleştirme",
    "visualization_desc": "Veri görselleştirme ve grafikler.",
    "workflow_title": "İş Akışı",
    "workflow_desc": "Süreç ve onay iş akışları.",
    "user_experience_title": "Kullanıcı Deneyimi",
    "user_experience_desc": "Kullanıcı geri bildirimleri ve deneyim analizi.",
    "tracking_title": "İzleme",
    "tracking_desc": "Performans ve hedef izleme.",
    "tsrs_title": "TSRS",
    "tsrs_desc": "Türkiye Sürdürülebilirlik Raporlama Standartları.",
    "ungc_title": "UN Global Compact",
    "ungc_desc": "Birleşmiş Milletler Küresel İlkeler Sözleşmesi.",
    "skdm_title": "SKDM",
    "skdm_desc": "Sınırda Karbon Düzenleme Mekanizması.",
    "standards_title": "Standartlar",
    "standards_desc": "Uluslararası sürdürülebilirlik standartları.",
    "strategic_title": "Stratejik Planlama",
    "strategic_desc": "Uzun vadeli strateji ve yol haritası.",
    "quality_title": "Kalite Yönetimi",
    "quality_desc": "Kalite standartları ve süreç iyileştirme.",
    "sasb_add_title": "SASB Verisi Ekle",
    "tcfd_governance": "TCFD Yönetişim",
    "tcfd_strategy": "TCFD Strateji",
    "tcfd_risk_mgmt": "TCFD Risk Yönetimi",
    "tcfd_metrics": "TCFD Metrikler",
    "tnfd_pillar_gov": "TNFD Yönetişim",
    "tnfd_pillar_strat": "TNFD Strateji",
    "tnfd_pillar_risk": "TNFD Risk Yönetimi",
    "tnfd_pillar_metrics": "TNFD Metrikler",
    
    # Specific missing keys
    "sc_risk_high": "Yüksek",
    "sc_risk_medium": "Orta",
    "sc_risk_low": "Düşük",
    "sc_type_material": "Malzeme",
    "sc_type_service": "Hizmet",
    "sc_type_logistics": "Lojistik",
    "sc_type_other": "Diğer",
    "water_source": "Su Kaynağı",
    "water_type": "Su Türü",
    "surface_water": "Yüzey Suyu",
    "ground_water": "Yeraltı Suyu",
    "municipal_water": "Şebeke Suyu",
    "recycled_water": "Geri Dönüştürülmüş Su",
    "waste_type": "Atık Türü",
    "hazardous": "Tehlikeli",
    "non_hazardous": "Tehlikesiz",
    "disposal_method": "Bertaraf Yöntemi",
    "recycling": "Geri Dönüşüm",
    "landfill": "Depolama",
    "incineration": "Yakma",
    "energy_type": "Enerji Türü",
    "electricity": "Elektrik",
    "natural_gas": "Doğalgaz",
    "diesel": "Dizel",
    "renewable": "Yenilenebilir",
    "solar": "Güneş",
    "wind": "Rüzgar",
    "hydro": "Hidro",
    "biomass": "Biyokütle",
    "geothermal": "Jeotermal",
    "scope_1": "Kapsam 1",
    "scope_2": "Kapsam 2",
    "scope_3": "Kapsam 3",
    "scope_1_desc": "Doğrudan emisyonlar",
    "scope_2_desc": "Satın alınan enerji kaynaklı dolaylı emisyonlar",
    "scope_3_desc": "Değer zinciri kaynaklı diğer dolaylı emisyonlar",
    "emission_factor": "Emisyon Faktörü",
    "activity_data": "Aktivite Verisi",
    "calculated_emission": "Hesaplanan Emisyon",
    "target_year": "Hedef Yılı",
    "base_year": "Baz Yılı",
    "reduction_target": "Azaltım Hedefi",
    "current_status": "Mevcut Durum",
    "on_track": "Yolunda",
    "at_risk": "Riskli",
    "delayed": "Gecikmiş",
    "completed": "Tamamlandı"
}

try:
    with open(TR_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)
except FileNotFoundError:
    data = {}

# Update with Turkish values
data.update(TURKISH_UPDATES)

with open(TR_FILE, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Updated {TR_FILE} with {len(TURKISH_UPDATES)} Turkish translations.")
