import json
import os

# Define the manual mapping of keys to Turkish values
TR_MAPPING = {
    "login_title": "Giriş Yap",
    "email_label": "E-posta Adresi",
    "password_label": "Şifre",
    "remember_me": "Beni Hatırla",
    "forgot_password_link": "Şifremi Unuttum",
    "login_btn": "Giriş Yap",
    "forgot_password_title": "Şifremi Unuttum",
    "forgot_password_desc": "E-posta adresinizi girin, size şifre sıfırlama bağlantısı gönderelim.",
    "send_reset_link_btn": "Sıfırlama Bağlantısı Gönder",
    "back_to_login": "Giriş Sayfasına Dön",
    "reset_password_title": "Şifre Sıfırlama",
    "new_password_label": "Yeni Şifre",
    "confirm_password_label": "Yeni Şifre (Tekrar)",
    "reset_password_btn": "Şifreyi Sıfırla",
    "verify_2fa_title": "İki Faktörlü Doğrulama",
    "verify_2fa_desc": "Lütfen kimlik doğrulama uygulamanızdaki kodu girin.",
    "code_label": "Doğrulama Kodu",
    "verify_btn": "Doğrula",
    "use_backup_code_link": "Yedek Kod Kullan",
    "backup_code_label": "Yedek Kod",
    "use_auth_app_link": "Kimlik Doğrulama Uygulaması Kullan",
    "2fa_management_desc": "Kullanıcılar için iki faktörlü doğrulama ve yedek kod yönetimi",
    "2fa_management_title": "2FA Yönetimi",
    "back_btn": "Geri",
    "backup_codes_info": "Her kod yalnızca bir kez kullanılabilir",
    "backup_codes_title": "Yedek Kodlar",
    "captcha_placeholder": "Resimdeki kodu girin",
    "disable_2fa_btn": "2FA'yı Kapat",
    "enable_2fa_btn": "2FA'yı Etkinleştir",
    "enter_code_msg": "Lütfen e-posta adresinize gönderilen 6 haneli kodu girin.",
    "force_2fa_label": "Tüm kullanıcılar için 2FA zorunlu olsun",
    "force_2fa_setting": "Zorunlu 2FA Ayarı",
    "qr_code_label": "QR Kod",
    "refresh_btn": "Yenile",
    "regenerate_backup_codes": "Yedek Kodları Yenile",
    "save_btn": "Kaydet",
    "security_code_label": "Güvenlik Kodu",
    "show_backup_codes": "Yedek Kodları Göster",
    "status_unknown": "Bilinmiyor",
    "user_and_status": "Kullanıcı ve Durum",
    "user_label": "Kullanıcı",
    "verification_code_label": "Doğrulama Kodu",
    "verification_code_title": "Doğrulama Kodu",
    "verification_title": "Doğrulama",
    "status_active": "Aktif",
    "status_passive": "Pasif",
    "status_label": "Durum",
    "action_create_report": "Rapor Oluştur",
    "action_enter_data": "Veri Girişi Yap",
    "action_enter_data_short": "Veri Gir",
    "action_view_details": "Detayları Gör",
    "admin_only_access": "Sadece yönetici erişimi",
    "average_score": "Ortalama Puan",
    "carbon_emissions": "Karbon Emisyonları",
    "category_compliance": "Uyumluluk",
    "completed_reports": "Tamamlanan Raporlar",
    "completion": "Tamamlanma",
    "cookie_accept": "Kabul Et",
    "cookie_msg": "Bu site, deneyiminizi iyileştirmek için çerezleri kullanır.",
    "copyright_sustainage": "Tüm hakları saklıdır.",
    "create_report_btn": "Rapor Oluştur",
    "dark_mode": "Karanlık Mod",
    "dashboard_load_error": "Kontrol paneli yüklenirken hata oluştu.",
    "dashboard_title": "Kontrol Paneli",
    "data_fetch_error": "Veri alınırken hata oluştu.",
    "datetime": "Tarih/Saat",
    "doc_account_settings_admin": "Yönetici Hesap Ayarları",
    "doc_account_settings_desc": "Hesap ayarlarınızı buradan yönetebilirsiniz.",
    "doc_account_settings_title": "Hesap Ayarları",
    "doc_data_entry_desc": "Veri girişi işlemlerini buradan yapabilirsiniz.",
    "doc_data_entry_step1": "Adım 1: Modül Seçin",
    "doc_data_entry_step2": "Adım 2: Veri Girin",
    "doc_data_entry_step3": "Adım 3: Kaydedin",
    "doc_data_entry_step4": "Adım 4: Onaylayın",
    "doc_data_entry_title": "Veri Girişi Kılavuzu",
    "doc_nav_help": "Yardım",
    "doc_reporting_desc": "Raporlama araçları ve özellikleri.",
    "doc_reporting_title": "Raporlama",
    "doc_welcome_desc": "Sustainage platformuna hoş geldiniz.",
    "doc_welcome_title": "Hoş Geldiniz",
    "error_add": "Ekleme Hatası",
    "error_occurred": "Bir hata oluştu",
    "export_button": "Dışa Aktar",
    "footer_contact_us": "İletişim",
    "footer_copyright": "Telif Hakkı",
    "footer_dpa": "Veri İşleme Sözleşmesi",
    "footer_help_center": "Yardım Merkezi",
    "footer_legal": "Yasal",
    "footer_privacy": "Gizlilik Politikası",
    "footer_sla": "Hizmet Düzeyi Sözleşmesi (SLA)",
    "footer_slogan": "Sürdürülebilirlik için akıllı çözümler.",
    "footer_support": "Destek",
    "last_update": "Son Güncelleme",
    "light_mode": "Aydınlık Mod",
    "loading": "Yükleniyor...",
    "logging_in": "Giriş yapılıyor...",
    "login_button": "Giriş",
    "login_failed": "Giriş başarısız",
    "manager_not_active": "Yönetici aktif değil",
    "mark_all_read": "Tümünü Okundu İşaretle",
    "module_not_active": "Modül aktif değil",
    "next_deadline": "Sonraki Teslim Tarihi",
    "no_notifications": "Bildirim yok",
    "notifications": "Bildirimler",
    "password": "Şifre",
    "pending_alerts_suffix": "bekleyen uyarı",
    "performance_score": "Performans Puanı",
    "record_added_error": "Kayıt eklenirken hata oluştu",
    "record_added_success": "Kayıt başarıyla eklendi",
    "retry_button": "Tekrar Dene",
    "role_create_error": "Rol oluşturma hatası",
    "role_create_success": "Rol başarıyla oluşturuldu",
    "role_delete_error": "Rol silme hatası",
    "role_delete_success": "Rol başarıyla silindi",
    "role_not_found": "Rol bulunamadı",
    "role_system_delete_error": "Sistem rolü silinemez",
    "role_system_edit_error": "Sistem rolü düzenlenemez",
    "role_update_error": "Rol güncelleme hatası",
    "role_update_success": "Rol başarıyla güncellendi",
    "server_error": "Sunucu hatası",
    "session_expired": "Oturum süresi doldu",
    "settings_updated": "Ayarlar güncellendi",
    "share_button": "Paylaş",
    "status_pending": "Beklemede",
    "success_add": "Başarıyla Eklendi",
    "survey_status": "Anket Durumu",
    "system_alert_title": "Sistem Uyarısı",
    "system_error": "Sistem Hatası",
    "top_performance_metrics": "En İyi Performans Metrikleri",
    "unauthorized_access": "Yetkisiz Erişim",
    "username": "Kullanıcı Adı",
    "view_all": "Tümünü Gör",
    "weights_reset": "Ağırlıklar sıfırlandı",
    "weights_updated": "Ağırlıklar güncellendi",
    "dashboard_page_title": "Kontrol Paneli",
    "dashboard_role_admin": "Adminler kullanıcı, şirket ve sistem ayarlarını yönetebilir.",
    "dashboard_role_help_desc": "Rolünüze göre erişebileceğiniz menüler ve modüller değişir.",
    "dashboard_role_help_title": "Rolünüz ve Yetkileriniz",
    "dashboard_role_super_admin": "Süper admin tüm ayar ve lisans yönetimine erişebilir.",
    "dashboard_role_user": "Kullanıcılar veri girişi yapabilir ve raporları görüntüleyebilir.",
    "getting_started_step1_desc": "Raporlama için kullanılacak temel şirket ve iletişim bilgilerini doldurun.",
    "getting_started_step1_link": "Firma Bilgilerine Git",
    "getting_started_step1_title": "Şirket bilgilerinizi tamamlayın",
    "getting_started_step2_desc": "Sürdürülebilirlik önceliklerinizi ve ilgili SDG/ESG konularını seçin.",
    "getting_started_step2_link": "SDG Modülüne Git",
    "getting_started_step2_title": "Öncelikli konuları ve SDG hedeflerini belirleyin",
    "getting_started_step3_desc": "Karbon, enerji, su ve diğer verileri girdikten sonra standartlara uygun rapor üretin.",
    "getting_started_step3_link_data": "Veri Girişi Ekranına Git",
    "getting_started_step3_link_reports": "Raporlama Yol Haritasını Aç",
    "getting_started_step3_title": "Veri girin ve ilk raporunuzu oluşturun",
    "getting_started_title": "Başlarken: Önerilen İlk Adımlar",
    "help_q5": "Oturumum neden kendiliğinden kapanıyor?",
    "help_a5": "Güvenlik nedeniyle belirli bir süre işlem yapmadığınızda oturumunuz otomatik olarak sonlandırılır. Bu, hesabınızı yetkisiz erişimlere karşı korumak için tasarlanmış bir özelliktir. Çalışırken veri kaybı yaşamamak için kritik işlemler sırasında periyodik olarak kaydetmenizi öneririz.",
    "help_q6": "Farklı bir lokasyondan bağlanırken neden hata alıyorum?",
    "help_a6": "SustainAge lisansınız, güvenlik sebebiyle belirli IP adresleri veya alan adları ile sınırlandırılmış olabilir. Farklı bir lokasyondan bağlandığınızda erişim sorunları yaşarsanız, yetkili sistem yöneticiniz veya SustainAge destek ekibi ile iletişime geçerek lisans ayarlarınızı kontrol etmenizi öneririz.",
    "module_status_beta": "Beta",
    "no_data_admin_hint": "Yeni kayıt eklemek için yukarıdaki \"Yeni Veri Girişi\" butonunu kullanabilirsiniz.",
    "no_data_user_hint": "Veri girişi için sistem yöneticinizle iletişime geçebilirsiniz.",
    "reporting_flow_title": "Raporlama Yol Haritası",
    "reporting_flow_step1": "Öncelikle veri giriş modüllerinde (karbon, enerji, su vb.) ilgili döneme ait verilerinizi tamamlayın.",
    "reporting_flow_step2": "Ardından “Sürdürülebilirlik Raporlama Yolculuğu” ekranından hangi standart ve modülleri kullanacağınızı belirleyin.",
    "reporting_flow_step3": "Son olarak bu ekrandan oluşturduğunuz raporları görüntüleyebilir, indirebilir veya “Birleşik Rapor” ile tek dokümanda birleştirebilirsiniz.",
    "reporting_flow_btn_journey": "Raporlama Yolculuğunu Aç",
    "reporting_flow_btn_unified": "Birleşik Rapor Oluştur",
    "pending": "Beklemede",
    "data_flow_title": "Veri Girişi Akışı",
    "data_flow_step1": "Üstteki sekmelerden görmek istediğiniz veri türünü seçin.",
    "data_flow_step2": "Yeni kayıt eklemek için \"Yeni Veri Girişi\" butonuna tıklayın.",
    "data_flow_step3": "Kaydedilen kayıtlar ilgili sekmede listelenir ve raporlamada kullanılır."
}

def update_tr_values():
    tr_path = os.path.join("backend", "locales", "tr.json")
    
    try:
        with open(tr_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            
        updated_count = 0
        for key, value in TR_MAPPING.items():
            if key not in data or data[key] != value:
                data[key] = value
                updated_count += 1
                
        if updated_count > 0:
            with open(tr_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=4)
            print(f"Updated {updated_count} keys in {tr_path}")
        else:
            print("No updates needed.")
            
    except Exception as e:
        print(f"Error updating tr.json: {e}")

if __name__ == "__main__":
    update_tr_values()
